export const nigeriaStates = [
  { label: "Abia", value: "Abia", id: "Abia" },
  { label: "Adamawa", value: "Adamawa", id: "Adamawa" },
  { label: "Akwa Ibom", value: "Akwa Ibom", id: "Akwa Ibom" },
  { label: "Anambra", value: "Anambra", id: "Anambra" },
  { label: "Bauchi", value: "Bauchi", id: "Bauchi" },
  { label: "Bayelsa", value: "Bayelsa", id: "Bayelsa" },
  { label: "Benue", value: "Benue", id: "Benue" },
  { label: "Borno", value: "Borno", id: "Borno" },
  { label: "Cross River", value: "Cross River", id: "Cross River" },
  { label: "Delta", value: "Delta", id: "Delta" },
  { label: "Ebonyi", value: "Ebonyi", id: "Ebonyi" },
  { label: "Edo", value: "Edo", id: "Edo" },
  { label: "Ekiti", value: "Ekiti", id: "Ekiti" },
  { label: "Enugu", value: "Enugu", id: "Enugu" },
  { label: "Gombe", value: "Gombe", id: "Gombe" },
  { label: "Imo", value: "Imo", id: "Imo" },
  { label: "Jigawa", value: "Jigawa", id: "Jigawa" },
  { label: "Kaduna", value: "Kaduna", id: "Kaduna" },
  { label: "Kano", value: "Kano", id: "Kano" },
  { label: "Katsina", value: "Katsina", id: "Katsina" },
  { label: "Kebbi", value: "Kebbi", id: "Kebbi" },
  { label: "Kogi", value: "Kogi", id: "Kogi" },
  { label: "Kwara", value: "Kwara", id: "Kwara" },
  { label: "Lagos", value: "Lagos", id: "Lagos" },
  { label: "Nasarawa", value: "Nasarawa", id: "Nasarawa" },
  { label: "Niger", value: "Niger", id: "Niger" },
  { label: "Ogun", value: "Ogun", id: "Ogun" },
  { label: "Ondo", value: "Ondo", id: "Ondo" },
  { label: "Osun", value: "Osun", id: "Osun" },
  { label: "Oyo", value: "Oyo", id: "Oyo" },
  { label: "Plateau", value: "Plateau", id: "Plateau" },
  { label: "Rivers", value: "Rivers", id: "Rivers" },
  { label: "Sokoto", value: "Sokoto", id: "Sokoto" },
  { label: "Taraba", value: "Taraba", id: "Taraba" },
  { label: "Yobe", value: "Yobe", id: "Yobe" },
  { label: "Zamfara", value: "Zamfara", id: "Zamfara" },
  { label: "FCT", value: "FCT", id: "FCT" },
];
